# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Path Signature
#'
#' Computes the signature of a path up to a specified order. The signature is a
#' sequence of iterated integrals that characterizes the path and has useful
#' properties for machine learning, quantitative finance, and time series analysis.
#'
#' @param path A numeric matrix with dimensions (n x d), where n is the number
#'   of time steps and d is the path dimension. Each row represents a time point
#'   and each column represents a dimension (standard time series format).
#' @param m An integer specifying the maximum order of the signature (1 <= m <= 10).
#' @param flat A logical value. If TRUE (default), returns a flattened numeric vector
#'   containing all signature levels concatenated. If FALSE, returns a list with
#'   each signature level as a separate element.
#'
#' @return If flat=TRUE, returns a numeric vector of length sum(d^k) for k=1 to m.
#'   If flat=FALSE, returns a list of length m, where element k contains a numeric
#'   vector of length d^k representing the k-th order signature.
#'
#' @details
#' The signature computation uses Chen's identity for efficient combination of
#' path segments. The function includes OpenMP parallelization and optimized
#' memory management.
#'
#' Memory usage grows as sum(d^k) for k=1 to m. For large dimensions or orders,
#' consider using lower values to avoid memory issues.
#'
#' The input follows standard time series convention: rows are time points,
#' columns are variables/dimensions.
#'
#' @examples
#' \dontrun{
#' # Create a simple 2D path (100 time points, 2 dimensions)
#' path <- matrix(rnorm(200), ncol = 2)
#'
#' # Or using cumulative sums for more realistic paths
#' path <- apply(matrix(rnorm(200), ncol = 2), 2, cumsum)
#'
#' # Compute signature up to order 3
#' sig_flat <- sig(path, m = 3, flat = TRUE)
#' sig_list <- sig(path, m = 3, flat = FALSE)
#' }
#'
#' @export
sig <- function(path, m, flat = TRUE) {
    .Call(`_SimpleSig_sig`, path, m, flat)
}

#' Get Signature Dimensions
#'
#' Returns the dimensions of each signature level for given path dimension and order.
#'
#' @param d An integer specifying the path dimension.
#' @param m An integer specifying the maximum signature order.
#'
#' @return An integer vector of length m, where element k contains the dimension
#'   of the k-th order signature (d^k).
#'
#' @examples
#' \dontrun{
#' dims <- sig_dimensions(3, 4)  # c(3, 9, 27, 81)
#' total_length <- sum(dims)     # 120
#' }
#'
#' @export
sig_dimensions <- function(d, m) {
    .Call(`_SimpleSig_sig_dimensions`, d, m)
}

